import jsonToGraphql from "@walmartlabs/json-to-simple-graphql-schema/lib/index.js";
import path from 'path';
import { promises as fs } from 'fs';

const { jsonToSchema } = jsonToGraphql;
const [,, jsonPath, graphqlPath] = process.argv;
const directoryPath = path.join(path.resolve(), jsonPath);
const files = await fs.readdir(directoryPath);

for (const file of files) {
    const jsonFile = await fs.readFile(path.join(path.resolve(), `${jsonPath}${file}`));
    const schema = jsonToSchema({ jsonInput: jsonFile.toString() });
    const entity = file.replace('.json', '');
    const entityFormatted = `${entity.charAt(0).toUpperCase()}${entity.slice(1)}`;
    await fs.appendFile(path.join(path.resolve(), graphqlPath), `${schema.value.replace('AutogeneratedMainType', entityFormatted)}\n`);
}